### ISSUE TITLE
only one instance/ device + doesn't work with if -> then module

### ISSUE THREAD

**Issue by pmbert** [maros/Zway-TimerSwitch#1]
Hello,
I'm a new z-way user (V2.2.3, UI V1.4.3), trying TimerSwitch V1.0. Hope it's correct what I'm doing.
1. Is it true that it's only possible to have 1 Timer in the system? I would need several timers for to switch more devices.
2. TimerSwitch doesn't work together with If -> Then App V2.0.5
for example if timer=on then switch device on
With ConditionSwitch V1.0.9 it works.
for example if timer > 0 then switch device on

**Comment by maros** [comment]
With the latest master you can now create multiple timer instances. Regarding the second issue i believe that this is a bug in "If -> Then App". Please file a bug against Z-Wave-Me/home-automation
